## Data Structures

##### heterogenous list 
##### zero based indexing
##### -ve indexing starts from back (-1 refers to the last element in the list)
##### mutable

In [1]:
sample_list = [1,13.6,"hi",12,1]
sample_list

[1, 13.6, 'hi', 12, 1]

In [2]:
sample_list[1]

13.6

In [3]:
sample_list[10]

IndexError: list index out of range

In [4]:
sample_list[-1]

1

In [5]:
sample_list[-2]

12

In [6]:
sample_list[-4]

13.6

In [7]:
sample_list[0]=100
sample_list

[100, 13.6, 'hi', 12, 1]

In [8]:
sample_list[-5]=1000
sample_list

[1000, 13.6, 'hi', 12, 1]

##### Tuple
##### heterogenous
##### paranthesis
##### immutable
##### can retrieve data using index

In [9]:
sample_tuple=(1,13.6,"hi",12,1)
sample_tuple

(1, 13.6, 'hi', 12, 1)

In [10]:
sample_tuple[0]=100
sample_tuple

TypeError: 'tuple' object does not support item assignment

### SET
##### doesnot allow duplicates
##### ordered first place
##### in set we cant access elements using index
##### set is mutable

In [11]:
sample_set = {1,12,32,45,1.6,"hi","king","apple","ball",1 , 12}
sample_set

{1, 1.6, 12, 32, 45, 'apple', 'ball', 'hi', 'king'}

In [12]:
sample_set[-1]

TypeError: 'set' object is not subscriptable

In [13]:
sample_set[0]=100


TypeError: 'set' object does not support item assignment

In [14]:
sample_set.add(10000)

In [15]:
sample_set

{1, 1.6, 10000, 12, 32, 45, 'apple', 'ball', 'hi', 'king'}

In [16]:
sample_set.remove("hi")
sample_set

{1, 1.6, 10000, 12, 32, 45, 'apple', 'ball', 'king'}

In [17]:
sample_set.remove(12)
sample_set

{1, 1.6, 10000, 32, 45, 'apple', 'ball', 'king'}

### Dictionary

##### always key should be unique else it takes the latest value with the key
##### we can retrieve the value using key bhut we cant retrieve the key usinng value
##### dictionary is mutable
##### key should be unique 
##### values can be duplicated but key cant be

In [18]:
sample_dict = {1:"apple",2:35.4,3:"apple",2:"every",6:34,7:35.4}
sample_dict

{1: 'apple', 2: 'every', 3: 'apple', 6: 34, 7: 35.4}

In [19]:
sample_dict[7]

35.4

In [20]:
sample_dict["apple"]

KeyError: 'apple'

In [21]:
sample_dict[7]=100
sample_dict

{1: 'apple', 2: 'every', 3: 'apple', 6: 34, 7: 100}

##### adding a key pair to the dictionary

In [22]:
sample_dict[10]="business"
sample_dict

{1: 'apple', 2: 'every', 3: 'apple', 6: 34, 7: 100, 10: 'business'}

## Numpy:Package for multidimensional array

#### np is the alais of the numpy

### shift+tab -> tells the use of the functions along with the syntax

In [23]:
import numpy as np

In [24]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [25]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones(2,5)

TypeError: Cannot interpret '5' as a data type

In [37]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### create an array of zeros with 2 rows and 10 columns

In [38]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
np.zeros((10,2),int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
#### evenly distributed output 

In [41]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
np.linspace(0,2,8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [43]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [44]:
np.eye(5,int)

TypeError: 'type' object cannot be interpreted as an integer

In [45]:
np.eye((5),eye)

NameError: name 'eye' is not defined