In [1]:
import numpy as np

#### evertime "rand" generates from 0 to 1

In [2]:
np.random.rand(3,2)

array([[0.90069153, 0.93951485],
       [0.81291871, 0.03966745],
       [0.65977991, 0.67253221]])

In [3]:
np.random.rand(3,2)

array([[0.35964506, 0.53796638],
       [0.01243287, 0.64807956],
       [0.55857781, 0.88291283]])

In [4]:
np.random.rand(4,3)

array([[0.52495455, 0.698814  , 0.01308233],
       [0.20299491, 0.94318481, 0.31070019],
       [0.34886902, 0.65548521, 0.77799779],
       [0.87843569, 0.58175747, 0.38428939]])

#### everytime "random.randn" generates from -1 to 1

In [5]:
np.random.randn(3,2)

array([[-0.43114552,  1.40891413],
       [-0.08967522,  0.19029775],
       [-0.7474723 ,  0.97969651]])

In [ ]:
#### generates a random integer b/w the given range

In [6]:
np.random.randint(34,100)

42

In [7]:
np.random.randint(34,100)

45

In [8]:
np.random.randint(20,56,100)

array([24, 43, 43, 46, 33, 43, 42, 28, 53, 25, 46, 48, 54, 55, 21, 48, 21,
       41, 36, 26, 31, 53, 28, 30, 53, 53, 34, 51, 33, 46, 49, 30, 40, 46,
       51, 20, 40, 28, 22, 43, 25, 24, 39, 29, 27, 32, 44, 27, 28, 26, 29,
       26, 34, 40, 37, 43, 51, 35, 55, 26, 27, 25, 53, 20, 53, 29, 37, 25,
       35, 30, 51, 30, 25, 30, 31, 37, 55, 42, 45, 48, 43, 53, 24, 43, 53,
       48, 37, 20, 47, 41, 27, 29, 43, 33, 53, 24, 48, 33, 22, 22])

In [9]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
rand_array=np.random.randint(0,100,20)
rand_array

array([21, 51, 70, 65, 37, 95, 26,  4, 17, 97, 55, 65, 24, 65, 16,  3, 39,
       25, 21, 74])

In [11]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [12]:
sample_array.reshape(3,7)


ValueError: cannot reshape array of size 30 into shape (3,7)

In [13]:
rand_array.min()


3

In [ ]:
#### returns the index of the minimum value

In [14]:
rand_array.argmin()

15

In [15]:
sample_array.dtype()


TypeError: 'numpy.dtype[int32]' object is not callable

In [16]:
sample_array.dtype

dtype('int32')

In [18]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#### transpose of the matrix

In [19]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
sample_array[-3]

18

In [23]:
sample_array[3:7]

array([13, 14, 15, 16])

In [24]:
sample_array[3:7]=100
sample_array

array([ 10,  11,  12, 100, 100, 100, 100,  17,  18,  19,  20])

In [25]:
sample_array[0:7]

array([ 10,  11,  12, 100, 100, 100, 100])

In [26]:
subset_sample_array[0:7]
subset_sample_array

NameError: name 'subset_sample_array' is not defined

In [27]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([ 10,  11,  12, 100, 100, 100, 100])

In [28]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,  100,  100,  100])

In [29]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [30]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

## Two-Dimensional array

In [31]:
np.std(sample_array)

472.6278741653062

In [32]:
sample_matrix = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
sample_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
sample_matrix[1][2]


7

In [34]:
sample_matrix[2,:]

array([ 9, 10, 11, 12])

In [35]:
sample_matrix[2]


array([ 9, 10, 11, 12])

In [36]:
sample_matrix[:,(2,3)]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### Selection Techniques

In [37]:
sample_array=np.arange(1,20)

In [38]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [39]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [40]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [41]:
np.min(sample_array)

1

In [42]:
np.max(sample_array)

19

In [43]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [44]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [45]:
np.argmin(sample_array)

0

In [46]:
np.argmax(sample_array)

18

In [47]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [48]:
np.std(sample_array)

5.477225575051661

In [49]:
np.var(sample_array)

30.0

In [50]:
np.mean(sample_array)

10.0

In [51]:
array=np.random.randn(3,2)

In [52]:
array

array([[-0.27462313, -0.31006458],
       [-0.54296219, -1.09792391],
       [-0.89831887, -1.33768633]])

In [53]:
np.round(array,decimals=4)

array([[-0.2746, -0.3101],
       [-0.543 , -1.0979],
       [-0.8983, -1.3377]])

In [54]:
sports=np.array(['golf','cricket','fball','cricket','football'])
np.unique(sports)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')

In [55]:
import pandas as pd
import numpy as np

In [56]:
labels=['w','x','y','z']
sample_lists=[100,200,300,400]
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}

In [63]:
pd.series(data=sample_lists)

AttributeError: module 'pandas' has no attribute 'series'

In [61]:
pd.Series(data=sample_lists)

0    100
1    200
2    300
3    400
dtype: int64

In [59]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [62]:
pd.Series(sample_lists,labels)

w    100
x    200
y    300
z    400
dtype: int64

In [64]:
pd.Series(data=sample_lists,index=labels)

w    100
x    200
y    300
z    400
dtype: int64

In [65]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [66]:
sports1['cricket']

1

In [67]:
sports2=pd.Series([1,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     1
football    2
baseball    3
golf        4
dtype: int64

In [68]:
sports1+sports2

baseball      NaN
basketball    NaN
cricket       2.0
football      4.0
golf          8.0
dtype: float64

In [69]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.276363  0.095647  0.805177  0.460335  0.447256
B  0.649195  0.994391  0.429159  0.920683  0.223775
C  0.132715  0.800296  0.218712  0.859311  0.655764
D  0.231125  0.497684  0.490571  0.523313  0.019498
E  0.386069  0.632815  0.379200  0.138994  0.857913
F  0.729973  0.988154  0.500978  0.763731  0.184495
G  0.374276  0.421372  0.273813  0.877460  0.997441
H  0.175550  0.298125  0.295718  0.260099  0.338517

In [70]:
df1["Score3"]

A    0.805177
B    0.429159
C    0.218712
D    0.490571
E    0.379200
F    0.500978
G    0.273813
H    0.295718
Name: Score3, dtype: float64

In [71]:
df1[["Score1","Score2","Score3"]]

Score1    Score2    Score3
A  0.276363  0.095647  0.805177
B  0.649195  0.994391  0.429159
C  0.132715  0.800296  0.218712
D  0.231125  0.497684  0.490571
E  0.386069  0.632815  0.379200
F  0.729973  0.988154  0.500978
G  0.374276  0.421372  0.273813
H  0.175550  0.298125  0.295718

In [72]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.276363  0.095647  0.805177  0.460335  0.447256  0.372011
B  0.649195  0.994391  0.429159  0.920683  0.223775  1.643586
C  0.132715  0.800296  0.218712  0.859311  0.655764  0.933011
D  0.231125  0.497684  0.490571  0.523313  0.019498  0.728809
E  0.386069  0.632815  0.379200  0.138994  0.857913  1.018884
F  0.729973  0.988154  0.500978  0.763731  0.184495  1.718127
G  0.374276  0.421372  0.273813  0.877460  0.997441  0.795649
H  0.175550  0.298125  0.295718  0.260099  0.338517  0.473676

In [73]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [74]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [75]:
df[["ID","Name"]]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally

In [76]:
df.drop("ID",axis=1)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

#### this takes the axis = 0 because its the default value

In [77]:
df.drop(3)

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
4  176  Lally     123

### How to import data using pandas

In [79]:
import numpy as np
import pandas as pd


In [80]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Financial-Analytics-Loan-Approval-Prediction/main/loan_prediction.csv")

In [81]:
df.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [82]:
df.sample(10)

Loan_ID  Gender Married Dependents Education Self_Employed  \
455  LP002455    Male     Yes          2  Graduate            No   
427  LP002368    Male     Yes          2  Graduate            No   
525  LP002699    Male     Yes          2  Graduate           Yes   
168  LP001579    Male      No          0  Graduate            No   
578  LP002877    Male     Yes          1  Graduate            No   
297  LP001954  Female     Yes          1  Graduate            No   
260  LP001865    Male     Yes          1  Graduate            No   
433  LP002387    Male     Yes          0  Graduate            No   
555  LP002792    Male     Yes          1  Graduate            No   
604  LP002959  Female     Yes          1  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
455             3859                0.0        96.0             360.0   
427             5935                0.0       133.0             360.0   
525            17500                0.0       400.0             360.0   
168             2237                0.0        63.0             480.0   
578             1782             2232.0       107.0             360.0   
297             4666                0.0       135.0             360.0   
260             6083             4250.0       330.0             360.0   
433             2425             2340.0       143.0             360.0   
555             5468             1032.0        26.0             360.0   
604            12000                0.0       496.0             360.0   

     Credit_History Property_Area Loan_Status  
455             1.0     Semiurban           Y  
427             1.0     Semiurban           Y  
525             1.0         Rural           Y  
168             0.0     Semiurban           N  
578             1.0         Rural           Y  
297             1.0         Urban           Y  
260             NaN         Urban           Y  
433             1.0     Semiurban           Y  
555             1.0     Semiurban           Y  
604             1.0     Semiurban           Y

In [83]:
df.shape

(614, 13)

In [84]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [86]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [87]:
df.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [88]:
df.tail(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
604            12000                0.0       496.0             360.0   
605             2400             3800.0         NaN             180.0   
606             3400             2500.0       173.0             360.0   
607             3987             1411.0       157.0             360.0   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
604             1.0     Semiurban           Y  
605             1.0         Urban           N  
606             1.0     Semiurban           Y  
607             1.0         Rural           Y  
608             1.0         Rural           Y  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [89]:
df.sample()

Loan_ID Gender Married Dependents Education Self_Employed  \
291  LP001938   Male     Yes          2  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
291             4400                0.0       127.0             360.0   

     Credit_History Property_Area Loan_Status  
291             0.0     Semiurban           N

In [90]:
df.sample()

Loan_ID Gender Married Dependents Education Self_Employed  \
526  LP002705   Male     Yes          0  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
526             3775                0.0       110.0             360.0   

     Credit_History Property_Area Loan_Status  
526             1.0     Semiurban           Y

In [91]:
df.sample(20)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
149  LP001520    Male     Yes          0      Graduate            No   
159  LP001552    Male     Yes          0      Graduate            No   
435  LP002393  Female     NaN        NaN      Graduate            No   
504  LP002619    Male     Yes          0  Not Graduate            No   
210  LP001708  Female      No          0      Graduate            No   
480  LP002534  Female      No          0  Not Graduate            No   
316  LP002035    Male     Yes          2      Graduate            No   
466  LP002500    Male     Yes         3+  Not Graduate            No   
398  LP002284    Male      No          0  Not Graduate            No   
351  LP002140    Male      No          0      Graduate            No   
357  LP002151    Male     Yes          1      Graduate            No   
336  LP002110    Male     Yes          1      Graduate           NaN   
552  LP002785    Male     Yes          1      Graduate            No   
358  LP002158    Male     Yes          0  Not Graduate            No   
508  LP002626    Male     Yes          0      Graduate           Yes   
289  LP001935    Male      No          0      Graduate            No   
437  LP002401    Male     Yes          0      Graduate            No   
77   LP001259    Male     Yes          1      Graduate           Yes   
137  LP001491    Male     Yes          2      Graduate           Yes   
168  LP001579    Male      No          0      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
149             4860              830.0       125.0             360.0   
159             4583             5625.0       255.0             360.0   
435            10047                0.0         NaN             240.0   
504             3814             1483.0       124.0             300.0   
210            10000                0.0       214.0             360.0   
480             4350                0.0       154.0             360.0   
316             3717                0.0       120.0             360.0   
466             2947             1664.0        70.0             180.0   
398             3902             1666.0       109.0             360.0   
351             8750             4167.0       308.0             360.0   
357             3875                0.0        67.0             360.0   
336             5250              688.0       160.0             360.0   
552             3333             3250.0       158.0             360.0   
358             3000             1666.0       100.0             480.0   
508             2479             3013.0       188.0             360.0   
289             9508                0.0       187.0             360.0   
437             2213             1125.0         NaN             360.0   
77              1000             3022.0       110.0             360.0   
137             3316             3500.0        88.0             360.0   
168             2237                0.0        63.0             480.0   

     Credit_History Property_Area Loan_Status  
149             1.0     Semiurban           Y  
159             1.0     Semiurban           Y  
435             1.0     Semiurban           Y  
504             1.0     Semiurban           Y  
210             1.0     Semiurban           N  
480             1.0         Rural           Y  
316             1.0     Semiurban           Y  
466             0.0         Urban           N  
398             1.0         Rural           Y  
351             1.0         Rural           N  
357             1.0         Urban           N  
336             1.0         Rural           Y  
552             1.0         Urban           Y  
358             0.0         Urban           N  
508             1.0         Urban           Y  
289             1.0         Rural           Y  
437             1.0         Urban           Y  
77              1.0         Urban           N  
137             1.0         Urban           Y  

In [93]:
df.shape

(614, 13)

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [95]:
df.isnull()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0      False   False    False       False      False          False   
1      False   False    False       False      False          False   
2      False   False    False       False      False          False   
3      False   False    False       False      False          False   
4      False   False    False       False      False          False   
..       ...     ...      ...         ...        ...            ...   
609    False   False    False       False      False          False   
610    False   False    False       False      False          False   
611    False   False    False       False      False          False   
612    False   False    False       False      False          False   
613    False   False    False       False      False          False   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              False              False        True             False   
1              False              False       False             False   
2              False              False       False             False   
3              False              False       False             False   
4              False              False       False             False   
..               ...                ...         ...               ...   
609            False              False       False             False   
610            False              False       False             False   
611            False              False       False             False   
612            False              False       False             False   
613            False              False       False             False   

     Credit_History  Property_Area  Loan_Status  
0             False          False        False  
1             False          False        False  
2             False          False        False  
3             False          False        False  
4             False          False        False  
..              ...            ...          ...  
609           False          False        False  
610           False          False        False  
611           False          False        False  
612           False          False        False  
613           False          False        False  

[614 rows x 13 columns]

In [96]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64